# Generated by Django 5.2.17 on 2026-09-21 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptBudget',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('approval_evidence', models.CharField(max_length=200)),
                ('snapshot_path', models.TextField()),
                ('snapshot_digest', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('version_sha256', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=240)),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corpus.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('session_epoch', models.PositiveBigIntegerField(default=1)),
                ('quarantined', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='policy_singleton')],
            },
        ),
        migrations.CreateModel(
            name='PrivateFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(default='received', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corpus.locator')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corpus.locator')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=30)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('evidence_id', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_corpus_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_grants', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.collection')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'collection', 'valid_until'], name='grant_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='grant_interval'), models.CheckConstraint(condition=models.Q(('evidence_id', ''), _negated=True), name='grant_evidence')],
            },
        ),
        migrations.AddConstraint(
            model_name='locator',
            constraint=models.UniqueConstraint(fields=('collection', 'uid', 'version_sha256'), name='locator_unique'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='membership_unique'),
        ),
        migrations.AddConstraint(
            model_name='privatefeedback',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['extraction', 'metadata', 'access', 'other'])), name='feedback_category'),
        ),
        migrations.AddConstraint(
            model_name='privatefeedback',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'received')), name='feedback_initial_status'),
        ),
        migrations.AddConstraint(
            model_name='savedreference',
            constraint=models.UniqueConstraint(fields=('owner', 'locator'), name='reference_unique'),
        ),
    ]
